# Generated by Django 5.2.4 on 2025-07-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_country', models.CharField(max_length=64)),
                ('num_of_nights', models.IntegerField(max_length=64)),
                ('destination_country', models.CharField(max_length=64)),
                ('price', models.IntegerField(max_length=64)),
            ],
        ),
    ]
